### ISSUE TITLE
Add redux-observables for async flow handling in demo/examples

### ISSUE THREAD

**Issue by Waterstraal** [piotrwitek/react-ts-jspm-starter-kit#19]

**Comment by piotrwitek** [comment]
yes it's already on my plate, I'm coming back to work in 2 days and continue working on this

**Comment by piotrwitek** [comment]
possible alternative to redux-saga: https://github.com/clarus/redux-ship

**Comment by cramhead** [comment]
I've been playing about a bit with [redux-observables](https://redux-observable.js.org/) as an alternative to sagas. I'm currently feeling that it will offer a more expressive and compact mechanism for higher level coordination logic in my app. It's very testable and performant too.

**Comment by piotrwitek** [comment]
@cramhead Unbelievable, because no more than a week ago in our newest project we are building from ground up, we came to the same conclusion and actually starting to experiment with redux-observables as a more powerful approach to Redux, and we are convinced to make a switch :)

Probably then I'll also make an examples with an unfinished Calculator example using redux-observables and my new cool way of 100% type safety for store, reducer, containers and components using TS 2.1.4 improved inferring mechanism instead explicitly typing interfaces everywhere and the cost that comes with managing them like keeping up to date with changes.

**Comment by cramhead** [comment]
Super cool. 
Also, the reduction in boilerplate with the new type inferencing will be awesome.

**Comment by Waterstraal** [comment]
We've actually opted for angular2 with [ngrx/store](https://github.com/ngrx/store) & [ngrx/effects](https://github.com/ngrx/effects), which is basicly redux with observables, because we found it extremely powerfull! I'm glad to see the React community is starting to see this now too!

**Comment by piotrwitek** [comment]
redux-observables WIP on this branch: https://github.com/piotrwitek/react-redux-typescript-starter-kit/tree/redux-observables
