### ISSUE TITLE
It's not working with IE

### ISSUE THREAD

**Issue by alexhumanbean** [piotrwitek/react-ts-jspm-starter-kit#49]
Hi, I'm trying to run this boilerplate. There are two issues:
1) It's not started after "npm start" (npm ERR! missing script: start), but it's working after "npm run dev"
2) It's not working with IE 11 - I see endless square in the middle of screen  (everything is OK with Google Chrome)

**Comment by piotrwitek** [comment]
thanks for report
1) there was problem with docs, `npm start` was removed, now there is only `npm run dev` - docs are fixed

2) development with IE is not supported, although prod version should work fine... 
- could you please confirm it by testing with "build for production workflow here": https://github.com/piotrwitek/react-redux-typescript-starter-kit#--build-for-production-workflow

**Comment by alexhumanbean** [comment]
Yes, the production version works fine with IE.
Thank you!

**Comment by piotrwitek** [comment]
@alexhumanbean cool thanks!
Please consider closing the issue if you don't have any more questions.
For rationale why IE is not supported in dev, is because I don't think IE is a good tool to do real web development, and I don't consider to waste my time into looking at this issue.
If this is something you are looking for, unfortunately you'll have to put your own effort to make it work.
